
[package]
name = "ggnet_derive"
version = "0.0.1"
authors = ["brambuurlage@gmail.com"]

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = { version ="0.14.8", features = ["extra-traits"] }
quote = "0.6"
byteorder = "1.2.2"
proc-macro2 = "0.4"