
[package]
name = "ggnet_derive"
version = "0.0.1"
authors = ["brambuurlage@gmail.com"]

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
byteorder = "1.2.2"